before_script:
- bin/rails db:create
dist: trusty
language: ruby
rvm:
- 2.5.0
script:
- bundle exec rspec
- bundle exec rails db:migrate RAILS_ENV=test
services:
- postgresql: '10.3'
dd:
  secure: TgmzOPwIaenlnv0rbs56zZke6l9Gdm5mIrr2zWA+W514XrnnoHfEgSHwuvG6EaMRQK1P6qblWAhER18ij9OjFEj0IO9IGDU2/JrwIbs0KtAO+pYWXOmBGzs8OKAZl00uHJbjhQ4zjT87cBIO8bj6cr/+z00G7CrBXGT9saQWJlutLt+xYS3caxFtYVZofGj9mStI5rU9tBSb7pmYpDUpqMbzmzpanX8nLEWBBf5+GLgkCpP8Z+MINy/IosrlnPb9O10schoM1hUI9EkUI3sq3PzZvxdiSeRA7mBbBblD7YL9eQIRcMAaNq65if2ElC+ijN332Dt8efcjMu6QXjmFsxptRp83fsEwmrjGB/7nY5T6FqtSWjjnrkHzYTe7ts2rZTbNkLt7+JXM+GXcNTk//PTgvjCpSYP7jNQvL3DwOdJj4XwXhFzR5djb5GWFGbpBzTpq16S+br8YbEKwYq9X82IgxnUkITLhG+5dhA/5J+O0LDCjl9MdYV5zaUbg7V4HYRrA7Q4Wx/HGT+0d4E4bxlmH48fDKOc3PDAvXHeu+GYQ4e+7unrkPXz6gDBg146NGWsZE9OTIO2dXNhXisIL0dJnagkhs0YF/BKUIi7t9gRDECtz3VEjkiOJluc2aGZHc+1anhANLr8JqmRKSEhGyCvPg34pSXSeVW/5vX21IBw=
